Repository holo-otaku/dst-frontend, pull requests merged in 2023-10, with the labels that each got.

#79 feature: add activity log page
  src/renderer/src/components/ActivtyLog/Interface.tsx
  src/renderer/src/components/ActivtyLog/index.tsx
  src/renderer/src/components/Navbar/Navbar.tsx
  src/renderer/src/routes/index.tsx
Labels: enhancement

#85 Fix: product search page recommend data list problem
  src/renderer/src/components/Navbar/Navbar.tsx
  src/renderer/src/components/Product/Search.tsx
  src/renderer/src/global.css
Labels: bug

#87 add series delete confirm
  src/renderer/src/components/Series/Delete.tsx
  src/renderer/src/components/Series/Table.tsx
Labels: good first issue

#92 feat: support after edit, back to search page restore search field
  src/renderer/src/components/Product/FilterFields/Boolean.tsx
  src/renderer/src/components/Product/FilterFields/Datetime.tsx
  src/renderer/src/components/Product/FilterFields/Number.tsx
  src/renderer/src/components/Product/FilterFields/String.tsx
  src/renderer/src/components/Product/FilterFields/index.tsx
  src/renderer/src/components/Product/FilterFields/types.tsx
  src/renderer/src/components/Product/Search.tsx
  src/renderer/src/components/Product/SearchBar.tsx
  src/renderer/src/hooks/pagination.tsx
Labels: enhancement

#61 release: 1.0.3
  package.json
  src/renderer/src/components/Account/Interfaces.tsx
  src/renderer/src/components/Account/Search.tsx
  src/renderer/src/components/Account/Table.tsx
  src/renderer/src/components/Account/index.tsx
  src/renderer/src/components/ActivtyLog/Interface.tsx
  src/renderer/src/components/ActivtyLog/index.tsx
  src/renderer/src/components/Breadcrumb/index.tsx
  src/renderer/src/components/Navbar/Navbar.tsx
  src/renderer/src/components/Pagination/Pagination.tsx
  src/renderer/src/components/Pagination/index.tsx
  src/renderer/src/components/Product/Create.tsx
  src/renderer/src/components/Product/Edit.tsx
  src/renderer/src/components/Product/FilterFields/Boolean.tsx
  src/renderer/src/components/Product/FilterFields/Datetime.tsx
  src/renderer/src/components/Product/FilterFields/Number.tsx
  src/renderer/src/components/Product/FilterFields/String.tsx
  src/renderer/src/components/Product/FilterFields/index.tsx
  src/renderer/src/components/Product/FilterFields/types.tsx
  src/renderer/src/components/Product/FormTable.tsx
  src/renderer/src/components/Product/Interface.tsx
  src/renderer/src/components/Product/ProductTable.tsx
  src/renderer/src/components/Product/Search.tsx
  src/renderer/src/components/Product/SearchBar.tsx
  src/renderer/src/components/Product/index.tsx
  src/renderer/src/components/Role/Create.tsx
  src/renderer/src/components/Role/Edit.tsx
  src/renderer/src/components/Role/Interfaces.tsx
  src/renderer/src/components/Role/PermissionTable.tsx
  src/renderer/src/components/Role/Search.tsx
  src/renderer/src/components/Role/Table.tsx
  src/renderer/src/components/Role/index.tsx
  src/renderer/src/components/Series/Create.tsx
  src/renderer/src/components/Series/Delete.tsx
  src/renderer/src/components/Series/Edit.tsx
  src/renderer/src/components/Series/Form.tsx
  src/renderer/src/components/Series/Interfaces.tsx
  src/renderer/src/components/Series/Management.tsx
  src/renderer/src/components/Series/Table.tsx
  src/renderer/src/components/Series/index.tsx
  src/renderer/src/global.css
  src/renderer/src/hooks/favoriteFilterField.tsx
  src/renderer/src/hooks/index.tsx
  src/renderer/src/hooks/pagination.tsx
  src/renderer/src/main.tsx
  src/renderer/src/routes/index.tsx
  yarn.lock
Labels: enhancement
